# version: "3.8"

services:
  backend:
    build: .
    container_name: quizmaster-backend
    ports:
      - "5000:5000"
    env_file:
      - ./docker.env
    depends_on:
      - redis
      - mailhog
    volumes:
      - ./backend:/app
    environment:
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025

  frontend:
    build: .
    container_name: quizmaster-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

  redis:
    image: redis:6.2
    container_name: quizmaster-redis
    ports:
      - "6379:6379"

  celery-worker:
    build: .
    container_name: quizmaster-celery-worker
    command: celery -A celery_app.celery worker --loglevel=info
    depends_on:
      - backend
      - redis
    env_file:
      - ./docker.env
    volumes:
      - ./backend:/app

  celery-beat:
    build: .
    container_name: quizmaster-celery-beat
    command: celery -A celery_app.celery beat --loglevel=info
    depends_on:
      - backend
      - redis
    env_file:
      - ./docker.env
    volumes:
      - ./backend:/app

  flower:
    build: .
    container_name: quizmaster-flower
    command: celery -A celery_app.celery flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - backend
      - redis
    env_file:
      - ./docker.env
    volumes:
      - ./backend:/app

  mailhog:
    image: mailhog/mailhog
    container_name: quizmaster-mailhog
    ports:
      - "8025:8025"
      - "1025:1025"